### ISSUE TITLE
Request: Dedicated volume mountable storage dir

### ISSUE THREAD

**Issue by codefriar** [GregYankovoy/docker-chowdown#3]
It would be great if I could mount a folder so that the .md files are stored outside of the docker image. (apart from the config)

**Comment by GregYankovoy** [comment]
Hi codefriar! Sorry I somehow missed this message.  I believe that support for this is already included.  

For instance, I am using the following run command:
docker run --name chowdown -d -p 4000:4000/tcp -v "/mnt/user/appdata/chowdown:/config" --restart=unless-stopped gregyankovoy/chowdown:latest

I can then access the recipes on my system via the directory /mnt/user/appdata/chowdown/_recipes.  Since they're mounted via a docker volume, the values should persist upon stop/start/update/delete of the container.  If you replace "/mnt/user/appdata/chowdown" with a suitable directory on your system, e.g. $(pwd) for the current directory, you should be good to go.

Let me know if you are having any issues and we can take a look.

Thanks,
Greg
